//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_62130516.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BangDiem
    {
        [Key]
        public System.Guid Id { get; set; }
        [Display(Name = "Mã số sinh viên")]
        public string MaSV { get; set; }
        [Display(Name = "Mã môn học")]
        public string MaMH { get; set; }
        [Display(Name = "Điểm quá trình")]
        public Nullable<decimal> DiemQT { get; set; }
        [Display(Name = "Điểm thi")]
        public Nullable<decimal> DiemThi { get; set; }
        [Display(Name = "Điểm tổng")]
        public Nullable<decimal> DiemTong { get; set; }
    
        public virtual HocPhan HocPhan { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
