//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_62130516.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangDiem
    {
        public System.Guid Id { get; set; }
        public string MaSV { get; set; }
        public string MaMH { get; set; }
        public Nullable<double> DiemQT { get; set; }
        public Nullable<double> DiemThi { get; set; }
        public Nullable<double> DiemTong { get; set; }
    
        public virtual HocPhan HocPhan { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
