//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_62130516.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GiangVien
    {
        public GiangVien()
        {
            this.HocPhans = new HashSet<HocPhan>();
        }

        [Key]
        [Display(Name = "Mã giáo viên")]
        public string MaGV { get; set; }

        [Display(Name = "Tên giáo viên")]
        public string TenGV { get; set; }

        [Display(Name = "Số điện thoại")]
        public string SDT { get; set; }

        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "Ngày sinh")]
        public DateTime DateOfBirth { get; set; }

        [Display(Name = "Trạng thái")]
        public Nullable<bool> DaXoa { get; set; }

        public virtual User User { get; set; }
        public virtual ICollection<HocPhan> HocPhans { get; set; }
    }
}
