//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_62130516.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiangVien
    {
        public GiangVien()
        {
            this.HocPhans = new HashSet<HocPhan>();
        }
    
        public string MaGV { get; set; }
        public string TenGV { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public DateTime DateOfBirth { get; set; }
        public bool DaXoa { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<HocPhan> HocPhans { get; set; }
    }
}
