//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_62130516.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocPhan
    {
        public HocPhan()
        {
            this.BangDiems = new HashSet<BangDiem>();
        }
    
        public string MaHP { get; set; }
        public string MaMon { get; set; }
        public string MaGV { get; set; }
    
        public virtual ICollection<BangDiem> BangDiems { get; set; }
        public virtual GiangVien GiangVien { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
