//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_62130516.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MonHoc
    {
        public MonHoc()
        {
            this.HocPhans = new HashSet<HocPhan>();
        }
        [Key]
        [Display(Name = "Mã môn học")]
        public string MaMH { get; set; }
        [Display(Name = "Tên môn học")]
        public string TenMon { get; set; }
        [Display(Name = "Số tín chỉ")]
        public Nullable<double> SoTinChi { get; set; }
    
        public virtual ICollection<HocPhan> HocPhans { get; set; }
    }
}
