//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_62130516.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHoc
    {
        public MonHoc()
        {
            this.HocPhans = new HashSet<HocPhan>();
        }
    
        public string MaMH { get; set; }
        public string TenMon { get; set; }
        public Nullable<double> SoTinChi { get; set; }
    
        public virtual ICollection<HocPhan> HocPhans { get; set; }
    }
}
