//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_62130516.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PhanQuyenTaiKhoan
    {
        public System.Guid Id { get; set; }
        [Display(Name = "Id người dùng")]
        public string UserId { get; set; }
        [Display(Name = "Mã quyền")]
        public Nullable<System.Guid> MaQuyen { get; set; }
    
        public virtual PhanQuyen PhanQuyen { get; set; }
        public virtual User User { get; set; }
    }
}
