//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_62130516.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PhanQuyen
    {
        public PhanQuyen()
        {
            this.PhanQuyenTaiKhoans = new HashSet<PhanQuyenTaiKhoan>();
        }
        [Key]
        [Display(Name = "Id quyền")]
        public System.Guid Id { get; set; }
        [Display(Name = "Tên quyền")]
        public string TenQuyen { get; set; }
    
        public virtual ICollection<PhanQuyenTaiKhoan> PhanQuyenTaiKhoans { get; set; }
    }
}
