//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_62130516.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public SinhVien()
        {
            this.BangDiems = new HashSet<BangDiem>();
        }
    
        public string MaSV { get; set; }
        public string TenSV { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string GioiTinh { get; set; }
        public Guid MaLop { get; set; }
        public bool DaXoa { get; set; }
    
        public virtual ICollection<BangDiem> BangDiems { get; set; }
        public virtual Lop Lop { get; set; }
    }
}
