//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_62130516.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.PhanQuyenTaiKhoans = new HashSet<PhanQuyenTaiKhoan>();
        }
    
        public string Id { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public bool DaXoa { get; set; }
        public string TenQuyen;
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual ICollection<PhanQuyenTaiKhoan> PhanQuyenTaiKhoans { get; set; }
    }
}
