//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_62130516.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public User()
        {
            this.PhanQuyenTaiKhoans = new HashSet<PhanQuyenTaiKhoan>();
        }
        [Key]
        [Display(Name = "Id Người dùng")]
        public string Id { get; set; }
        [Display(Name = "Tên đăng nhập")]
        public string TenDangNhap { get; set; }
        [Display(Name = "Mật khẩu")]
        public string MatKhau { get; set; }
        [Display(Name = "Trạng thái tài khoản")]
        public bool DaXoa { get; set; }
        [Display(Name = "Tên quyền")]
        public string TenQuyen;
        public virtual GiangVien GiangVien { get; set; }
        public virtual ICollection<PhanQuyenTaiKhoan> PhanQuyenTaiKhoans { get; set; }
    }
}
